import { Difficulty } from "@/features/questions";

export const historiesStub = [
  {
    id: "1",
    title: "1",
    categories: ["Strings"],
    difficulty: Difficulty.Hard,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-01-25T13:45:00"),
  },
  {
    id: "2",
    title: "2",
    categories: ["Strings", "Array", "Brain Teaser"],
    difficulty: Difficulty.Hard,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-05-17T09:30:00"),
  },
  {
    id: "3",
    title: "3",
    categories: ["Strings"],
    difficulty: Difficulty.Medium,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-08-21T15:20:00"),
  },
  {
    id: "4",
    title: "4",
    categories: ["Strings"],
    difficulty: Difficulty.Easy,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-02-11T11:50:00"),
  },
  {
    id: "5",
    title: "5",
    categories: ["Strings"],
    difficulty: Difficulty.Hard,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-12-30T08:15:00"),
  },
  {
    id: "6",
    title: "6",
    categories: ["Strings"],
    difficulty: Difficulty.Medium,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-07-19T19:45:00"),
  },
  {
    id: "7",
    title: "7",
    categories: ["Strings"],
    difficulty: Difficulty.Medium,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-03-23T17:30:00"),
  },
  {
    id: "8",
    title: "8",
    categories: ["Strings"],
    difficulty: Difficulty.Medium,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-10-05T14:00:00"),
  },
  {
    id: "9",
    title: "9",
    categories: ["Strings"],
    difficulty: Difficulty.Easy,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-04-18T10:25:00"),
  },
  {
    id: "10",
    title: "10",
    categories: ["Strings"],
    difficulty: Difficulty.Easy,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-11-12T16:40:00"),
  },
  {
    id: "11",
    title: "11",
    categories: ["Strings"],
    difficulty: Difficulty.Easy,
    description: "dasdasd",
    link: "http://localhost:3000/questions",
    timestamp: new Date("2021-09-07T21:05:00"),
  },
];
